version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      aws-cdk:
        patterns:
          - 'aws-cdk*'
          - '@aws-cdk/*'
      aws-sdk:
        patterns:
          - '@aws-sdk/*'
      types:
        patterns:
          - '@types/*'

  - package-ecosystem: pip
    directory: '/agent-runtime'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
